# Generated by Django 5.2.13 on 2026-04-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='face_encoding_sample',
            field=models.ImageField(blank=True, null=True, upload_to='face_samples/'),
        ),
    ]
