# Generated by Django 5.2.13 on 2026-04-15 15:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankuser_face_encoding_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='face_encoding_sample',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
